"""empty message

Revision ID: 0d1621969e1b
Revises: 13dd3914e8d9
Create Date: 2022-05-04 17:19:53.018475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1621969e1b'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('soundcloud', sa.String(length=120), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('soundcloud')
    )
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=120), nullable=False),
    sa.Column('notas', sa.String(length=200), nullable=False),
    sa.Column('donador_id', sa.Integer(), nullable=False),
    sa.Column('donatario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['donatario_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genero_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=120), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_donacion_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donacion_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['donacion_id'], ['donacion.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_favoritos_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favoritos_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['favoritos_id'], ['favoritos.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_post_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('perfil_post_notificacion')
    op.drop_table('perfil_favoritos_notificacion')
    op.drop_table('perfil_donacion_notificacion')
    op.drop_table('post')
    op.drop_table('genero_perfil')
    op.drop_table('favoritos')
    op.drop_table('donacion')
    op.drop_table('contacto')
    op.drop_table('perfil')
    op.drop_table('usuario')
    op.drop_table('genero')
    # ### end Alembic commands ###
