"""empty message

Revision ID: 4a6df4b8e0b7
Revises: 0d1621969e1b
Create Date: 2022-05-04 17:27:01.129059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6df4b8e0b7'
down_revision = '0d1621969e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_post_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('perfil_post_notificacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_post_notificacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='perfil_post_notificacion_post_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='perfil_post_notificacion_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='perfil_post_notificacion_pkey')
    )
    op.drop_table('usuario_post_notificacion')
    # ### end Alembic commands ###
